### ISSUE TITLE
Motion manager closure has incorrect argument types

### ISSUE THREAD

**Issue by melihkeskin** [ndmeiri/Panorific#2]
Hi,
When I run the project in Swift 2.1, I get this error. Can you help me on this matter?

> Cannot convert value of type '(CMDeviceMotion!, NSError!) -> Void' to expected argument type 'CMDeviceMotionHandler' (aka '(Optional<CMDeviceMotion>, Optional<NSError>) -> ()')

```
self.motionManager.startDeviceMotionUpdatesToQueue(NSOperationQueue.mainQueue(),
    withHandler: { (motion: CMDeviceMotion!, error: NSError!) -> Void in  // Error here
        self.calculateRotationBasedOnDeviceMotionRotationRate(motion)
    })
```

**Comment by ndmeiri** [comment]
Hi @melihkeskin,
Thanks for bringing this to my attention. Could you please try again with the latest commit to `master`?

**Comment by melihkeskin** [comment]
Hi again,

Thanks for your help.It worked well.

But :)

if the device orientation is lansdscape,
there is disturbance in the image size.it is not cover the screen.

this state is enough for me.

I wanted to just warn you about it.

Thanks for sharing

**Comment by ndmeiri** [comment]
@melihkeskin Thanks for the heads up. I'll open an issue to look into it when I get a chance.

**Comment by ndmeiri** [comment]
See #3
